server:
    port: localhost:10000

http:
    auth:
        key: user
        secret: password

db:
    mysql:
        user: root
        password: rootpass
        hostname: localhost
        dbname: notes
